### ISSUE TITLE
Show all response headers

### ISSUE THREAD

**Issue by DamirSvrtan** [infinum/dox#13]
Eventually add a config option to ignore certain headers (a blacklist), but I can live without having that option for now.

**Comment by DamirSvrtan** [comment]
Please list all the request headers also.

**Comment by melcha** [comment]
`request.headers` returns around 50 Rails specific headers, I didn't find a way to get only HTTP headers out so I added `headers_whitelist` config option with `Content-Type` whitelisted by default.

Requests and responses will now display all whitelisted headers, if any.

**Comment by DamirSvrtan** [comment]
Thnx :1st_place_medal:
