### ISSUE TITLE
Undefined method resource_groups inside document block

### ISSUE THREAD

**Issue by nevenRakonic** [infinum/dox#20]
When I try to use the ```resource_group``` method inside the ```document``` block I get a

```NoMethodError: undefined method 'resource_group' for #<Dox::DSL::Documentation:0x007fafb218fe20>```

e.g inside

```ruby
document :api do
  resource 'Foo' do
    endpoint '/foo'
    group 'Foo'
  end

  resource_group 'bar' do
  end
end
```

**Comment by melcha** [comment]
It's actually just `group`, not `resource_group` - typo in the documentation. Documentation updated.
