### ISSUE TITLE
Add attributes section

### ISSUE THREAD

**Issue by d4be4st** [infinum/dox#23]
https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#attributes-section

This is useful for post requests where you specify what attributes are valid, needed and their types

**Comment by melcha** [comment]
@d4be4st implemented a version of this in #36, but it doesn't work okay.

We're currently implementing version 2.0, we're replacing API Blueprint with OpenAPI (#46), and we don't need attributes for that, so I'm closing this.
