### ISSUE TITLE
Why Dox supports only JSON-type parameters in request?

### ISSUE THREAD

**Issue by veejar** [infinum/dox#29]
Hello

I have question related to parsing API Request Body.
https://github.com/infinum/dox/blob/master/lib/dox/entities/example.rb#L72
Why only JSON-type request is valid? My API allows RAW or JSON type parameters in requests to API. In tests I've used RAW-type and now I should to change a lot of code to use Dox.
Do you plan to add RAW-body support dependent on Content-Type header in request?

**Comment by melcha** [comment]
Hello @veejar,

we're aware of this only JSON format issue, we just haven't got the time to fix it yet. I hope we'll fix it within the next 2 weeks.

Please give me a bit more details about your problem.
Do you write controller or request tests? 
What Rails version are you using? 
And what exactly do you mean by RAW-type? Plain text or? A code example would be useful. 

Thanks.

**Comment by veejar** [comment]
Hello

I have a lot of RSpec request tests for my API application on Rails 5.1. For example:
```
require 'rails_helper'

describe 'POST /customers', type: :request do
  include Docs::Customers::Api
  include Docs::Customers::Create

  it "should create new customer", :dox do
    params = { first_name: "John", last_name: "Miller" }
    post customers_path, params: params
    expect(response).to be_success
  end
end
```
Running command for generating docs:
`bundle exec rspec spec/requests/order_items -f Dox::Formatter --order defined --tag dox --out doc/docs.md`

And getting error:
```
/Users/vadim/.rvm/gems/ruby-2.4.2/gems/json-1.8.6/lib/json/common.rb:155:in `parse': 784: unexpected token at 'first_name=John&last_name=Miller' (JSON::ParserError)
	from /Users/vadim/.rvm/gems/ruby-2.4.2/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
	from /Users/vadim/.rvm/gems/ruby-2.4.2/gems/dox-1.0.2/lib/dox/entities/example.rb:72:in `parse_request_body'
```
RAW-type request body: first_name=John&last_name=Miller
Content-Type: application/x-www-form-urlencoded

To fix that error I should change my RSpec test to:
```
require 'rails_helper'

describe 'POST /customers', type: :request do
  include Docs::Customers::Api
  include Docs::Customers::Create

  it "should create new customer", :dox do
    params = { first_name: "John", last_name: "Miller" }
    headers = { 'Content-Type' => 'application/json' }
    post customers_path, params: params.to_json, headers: headers
    expect(response).to be_success
  end
end
```
So, added json content-type header and params.to_json in request.

I have fixed that in my fork of dox-project:
https://github.com/veejar/dox/commit/40cb9776bc76ae5016ba1b05e631cfcff921a4f5

**Comment by melcha** [comment]
Hello @veejar, 

thanks for the detailed explanation.

We've finally released a new version with a fix for this JSON issue, please check it out: https://github.com/infinum/dox/commit/354f1c9350e21d6bd82a581eece904852f172a0f#diff-67a441db4c0fa3693b7a9b0915f0cd6aR84.

If a `content-type` header is JSON or XML, it will format and indent the request and response body properly (but the request and response bodies have to be in JSON or XML format). In other cases, it will print out plain payload string.

So, if you are writing an API and using the JSON format, you should use JSON payloads with proper headers in your tests as well, as you’ve shown on the example above.

If you use url encoded params, like in this test:
``` ruby
  it "should create new customer", :dox do
    params = { first_name: "John", last_name: "Miller" }
    post customers_path, params: params
    expect(response).to be_success
  end
```
you’ll get a plain text response output like this:
`first_name=John&last_name=Miller`

 with `content-type` `application/x-www-form-urlencoded`.
