### ISSUE TITLE
Attributes Section and Nested Attributes support

### ISSUE THREAD

**Issue by veejar** [infinum/dox#30]
Hello

Api Blueprint has Request Attributes Section:
https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-attributes-section

Also, Apiary supports MSON in request attributes description:
https://help.apiary.io/tools/interactive-documentation/

Added support of these features in my fork of dox-project:
https://github.com/veejar/dox/commit/d0f7127a006ebb98957c3fa0a1170d7a7e7bbc62

**Comment by selivandex** [comment]
Any news on this?

**Comment by d4be4st** [comment]
we moved from API blueprint to openapi 3.0 as API blueprint is no longer maintained
