### ISSUE TITLE
Question: is there any way to skip resource definition?

### ISSUE THREAD

**Issue by mojobiri** [infinum/dox#32]
Is it possible to render actions inside of a group to skip the unnecessary level of nesting?
![image](https://user-images.githubusercontent.com/664081/41842291-0cfb3178-7873-11e8-805a-bfcf6e653812.png)

Currently, I have redundant nesting:
![image](https://user-images.githubusercontent.com/664081/41842393-59d440e8-7873-11e8-90f4-dfc7a581942a.png)

**Comment by cilim** [comment]
Hi @mojobiri 👋 
Sorry for taking so long to respond 🙁 

I have an option for you!
You could namespace all of your API accessible resources in 1 group and that way you wouldn't have the redundant level of nesting for a resource. The file structure would therefore look like this:
```
/spec
  | docs
    | resources
      | campaigns
      | companies
      | contacts
      | interactions
```
and the `campaigns` could look like this:
```
module Docs
  module Resources
    module Campaigns
      extend Dox::DSL::Syntax

      document :api do
        resource 'Campaigns' do
          endpoint '/campaigns'
          group 'Resources'
        end
      end

      document :index do
        action 'GET campaigns'
      end

      document :show do
        action 'GET campaign'
      end
    end
  end
end
```

Sometimes it's really good to have another level of this nesting if you're adding descriptions (resource attributes, enumerations, etc...) so I don't think we'll be implementing an option to omit this behaviour in the near future.
