### ISSUE TITLE
Can not override action params to be empty

### ISSUE THREAD

**Issue by marcisv** [infinum/dox#33]
There are only internal params for an action that we use as route default params, but do not want to show in documentation.
I would expect that using
```
params({})
```
within an action should remove all the params, but it shows the default ones (that are passed within example request) instead.
Is this expected for some reason on needs a fix?

The current ugly workaround for me is
```
params(Struct.new(:presence).new({}))
```
as the gem is using `presence` internally.

**Comment by cilim** [comment]
Hi @marcisv 

The problem here is that dox is taking the controller `params` and rendering them in your documentation.

For example, if you have a users_controller where you add params to the ActionController::Parameters like this:

```
class UsersController < ApiController
  def create
    params[:some_new_parameter] = 'ParamValue'
    @user = User.new(params)
    respond_with(@user.save, serializer: UserSerializer)
  end
end
```

this would cause Dox to print out the `some_new_parameter` param. A way to avoid this is to not change the Rails controller `params`:

```
class UsersController < ApiController
  def create
    @user = User.new(permitted_params)
    respond_with(@user.save, serializer: UserSerializer)
  end

  private

  def permitted_params
    params.merge(some_new_parameter: 'ParamValue')
  end
end
```

Sorry for taking so long to respond. If you're still around, let me know if this helps your issue :)

**Comment by marcisv** [comment]
Hi, @cilim,

Thank you for the response. Here we had a case that we set the default param value already from routes, when using the same controller for different resources. Something like this:

```ruby
namespace :api do
  resources :posts, controller: "api", resource_name: "Post"
  resources :posts, controller: "api", resource_name: "Comment"
end
```

And we wanted that `resource_name` not to appear in docs. Maybe I have a lack of context why is it so, but is there any good reason for `params({})` to still keep the default values, if by default you can just omit the params call?

**Comment by cilim** [comment]
Yeah, the problem is that `{}.presence` returns `nil` and then your overridden params are ignored.

I opened a small [PR](https://github.com/infinum/dox/pull/41) and we'll merge it as soon as possible.

Thanks for reporting this bug! 🙂

**Comment by cilim** [comment]
@marcisv so sorry for the long wait, but we have finally found some time and released a new minor version. [1.2.0](https://rubygems.org/gems/dox/versions/1.2.0) is now available.

**Comment by marcisv** [comment]
@cilim Thank you for the fix 👍
