### ISSUE TITLE
headers_whitelist does not seem to be working

### ISSUE THREAD

**Issue by kushagr** [infinum/dox#40]
Hello, I'm using rails 5.2.2 with dox 1.1.0, I'm using request specs to generate documentation.
The headers included in the documentation are only 'Accept' and 'Content-Type'.

I added this to an initializer.
```
Dox.configure do |config|
  config.headers_whitelist = ['access-token', 'token-type', 'client', 'expiry', 'uid']
end

```

But this is not working, when I try and debug it and check the contents of full_headers_whitelist only shows 'Accept' and 'Content-Type'.
Am I missing something here?

Thanks

**Comment by cilim** [comment]
Hi @kushagr 👋 

The configuration should be added to the `spec/rails_helper.rb` file, not an initializer, because it's only necessary for the specs:

_rails_helper.rb_
```
require 'spec_helper'
require 'dox'

Dox.configure do |config|
  config.headers_whitelist = ['access-token', 'token-type', 'client', 'expiry', 'uid']
end
```

Make sure to put the Dox configuration after the `require 'dox'`.

Let me know if this solved your issue.

**Comment by kushagr** [comment]
Hey @cilim 
Thanks for the quick reply, I gave it a quick test and moved the config block after the require 'dox', with in the rails_helper.rb. It still does not list these variables in the documentation. 
Also checking the contents of `full_headers_whitelist` still shows only ['Accept', 'Content-Type']

**Comment by cilim** [comment]
Then the issue might be somewhere else...I'll paste you the code from my local small project that has everything in place:

_rails_helper.rb_
```
require 'spec_helper'
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../config/environment', __dir__)

require 'rspec/rails'
require 'dox'

# Load support files
Dir[Rails.root.join('spec', 'support', '**', '*.rb')].each { |f| require f }
# Load dox files
Dir[Rails.root.join('spec', 'docs', 'api', 'v1', '**', '*.rb')].each { |f| require f }

begin
  ActiveRecord::Migration.maintain_test_schema!
rescue ActiveRecord::PendingMigrationError => e
  puts e.to_s.strip
  exit 1
end
RSpec.configure do |config|
  config.fixture_path = "#{::Rails.root}/spec/fixtures"
  config.use_transactional_fixtures = true
  config.infer_spec_type_from_file_location!
  config.filter_rails_from_backtrace!

  config.after(:each, :dox) do |example|
    example.metadata[:request] = request
    example.metadata[:response] = response
  end
end

Dox.configure do |config|
  config.header_file_path = Rails.root.join(
    'spec', 'docs', 'api', 'v1', 'descriptions', 'header.md'
  )
  config.desc_folder_path = Rails.root.join('spec', 'docs', 'api', 'v1', 'descriptions')
  config.headers_whitelist = ['authorization']
end
```

_exhibitors_controller request spec_:
```
describe 'List exhibitors' do
  include Docs::Api::V1::Exhibitors::Api
  let(:user) { create(:user) }

  context 'when a user is logged in' do
    include Docs::Api::V1::Exhibitors::Index
    let(:exhibitors) { create_list(:exhibitor, 3) }

    let(:get_exhibitors) do
      exhibitors
      get 'api/v1/exhibitors', headers: {
        'content-type' => 'application/vnd.api+json',
        'accept' => 'application/vnd.api+json',
        'authorization' => "Bearer #{user.jti_token}"}
    end

    it 'returns exhibitors', :dox do
      get_exhibitors
      expect(response_array.size).to eq 3
    end
  end
end
```

And here's the screenshot of the new authorization header key:
<img width="656" alt="screenshot 2019-02-28 at 11 54 53" src="https://user-images.githubusercontent.com/4703945/53561662-c419ef80-3b4f-11e9-902f-a87f07adb8a8.png">

Maybe you didn't add any of the headers in the spec request example?

**Comment by kushagr** [comment]
Thank you! I got it to work from your example :)

Basically I was overriding the methods to add_auth_headers and Dox was being configured before those includes. Shifting it around solved to the issue.

Cheers :+1:
