### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by trende-jp** [infinum/dox#47]
Is this no longer being developed?

**Comment by melcha** [comment]
It is still being developed, we're preparing version 2.0. We're replacing API blueprint with [OpenAPI](https://github.com/OAI/OpenAPI-Specification) / [Redocly](https://github.com/Redocly/redoc).

It seems that [API blueprint]( https://github.com/apiaryio/api-blueprint) is no longer being maintained, and is lacking some features we'd like to have.

The DSL part will remain pretty much the same, we'll write migration instructions from 1.x to 2.x for other stuff (header etc). 

Pull request in progress: #46

**Comment by cilim** [comment]
@trende-jp in the meantime, you can safely use [1.2.0](https://rubygems.org/gems/dox/versions/1.2.0) in your projects.
Here are the [newest introduced changes](https://github.com/infinum/dox/blob/master/CHANGES.md#version-120).

Cheers! 👋

**Comment by n4rq5** [comment]
Can you please give us some update on when can we expect 2.0 to be released if at all?

**Comment by d4be4st** [comment]
We just released 2.0.0.beta1 with support for openapi 3.0
https://rubygems.org/gems/dox/versions/2.0.0.beta1
