### ISSUE TITLE
OpenAPI bug - description in action block

### ISSUE THREAD

**Issue by lovro-bikic** [infinum/dox#49]
There seems to be a bug on `feature/openapi` branch — descriptions added to action block are never rendered.

Steps to reproduce:
1. Add action block with desc
```ruby
document :create do
  action 'Create smth' do
    desc 'hello'
  end
end
```
2. Generate documentation

The action will be rendered in the generated documentation, but the description is missing. I've tried to pass both inline descriptions and markdown files, but none of them were rendered.

I think the bug is in `lib/dox/printers/action_printer.rb` file — https://github.com/infinum/dox/pull/46/files#diff-87105a834429cb75e9b69541c6dc3d68. There used to be code there which handled rendering descriptions, but it was removed.

**Comment by VKuzina** [comment]
Fixed https://github.com/infinum/dox/pull/46/commits/990a9b6a087cb2c67086a014e993063c6145bcc8

If there is still a problem reopen the issue.
